"""
Detection result operations — NeetTestGenerator_Detector table.
"""

from core.config import DYNAMO_DETECTOR_TABLE
from core.db_base import dynamo, now_iso


def create_detection_result(
    test_id: str,
    user_id: str,
    subject: str,
    medium: str,
    file_type: str,
    s3_paths: list,
    results: dict,
    success: bool = True,
    error_message: str = "",
    prompt_version: str = "v1",
) -> str:
    """
    Save detection output under the given test_id (generated by the caller —
    this is the same ID that will later identify the job and the finished test).
    results = {easy: {mcq: {count, min, max}, ...}, medium: {...}, hard: {...}}
    """
    table = dynamo().Table(DYNAMO_DETECTOR_TABLE)
    item = {
        "test_id":        test_id,
        "user_id":        user_id,
        "subject":        subject,
        "medium":         medium,
        "file_type":      file_type,
        "s3_paths":       s3_paths,
        "results":        results,
        "success":        success,
        "prompt_version": prompt_version,
        "created_at":     now_iso(),
    }
    if error_message:
        item["error_message"] = error_message
    table.put_item(Item=item)
    return test_id


def get_detection_result(test_id: str) -> dict | None:
    table = dynamo().Table(DYNAMO_DETECTOR_TABLE)
    resp = table.get_item(Key={"test_id": test_id})
    return resp.get("Item")
